### ISSUE TITLE
avoiding locations

### ISSUE THREAD

**Issue by arminakvn** [ercas/route_distances#1]
Valhalla api has an option for passing a set of location to be avoided when calculating the trip for a call. This is an example from a recent blog post: 
```
{"locations":[{"lat":39.795002,"lon":-76.362720}],"avoid_locations":[{"lat":39.815447,"lon":-76.325397}],"costing":"auto"

```

would be good to have it as optional argument for the class.

---
this is the example this is from: https://mapzen.com/blog/isochrones-washington_post/

**Comment by ercas** [comment]
Resolved #1: new "avoid" argument that accepts an array of (long, lat) pairs to avoid b9abea06517bbcb643afa6e01903d43e5507016b
